Repository ItJustWorksTM/EiffelVis, pull requests merged in 2022-01, with the labels that each got.

#77 backend: add readme files
  README.md
  backend/README.md
  backend/crates/eiffelvis_core/README.md
  backend/crates/eiffelvis_gen/README.md
  backend/crates/eiffelvis_http/README.md
  backend/crates/eiffelvis_stream/README.md
Labels: docs

#86 frontend: Added Graph Legend and Layout Options to Customize Layout
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.svelte
  frontend/src/apidefinition.ts
  frontend/src/layout.ts
Labels: fundamental, Frontend, UI

#85 [frontend] Add back G6 TimeBar to svelte frontend
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.svelte
  frontend/src/apidefinition.ts
  frontend/src/components/G6Graph.svelte
Labels: Frontend, UI

#89 frontend/eiffelvis.ts: add code documentation
  frontend/src/eiffelvis.ts
Labels: documentation

#90 frontend/graph: call .render() to actually reset the graph
  frontend/src/components/G6Graph.svelte
Labels: bug
